### ISSUE TITLE
Transformations Required

### ISSUE THREAD

**Issue by shaheensarafa** [simplify9/FluentOlap#15]
# Transformations

There needs to be proper transformations to handle data, changing their formats etc.

Multiple ways to go about this:
- Transformation Function Lanmbdas
- Ready made functions
- Etc

## Use Case
DateTime needing to be transformed before going into database.

---

I will be looking into a proper way to handle transformations.

**Comment by shaheensarafa** [comment]
@mahmoud-syr I have added a HasTransformation() lamda in the branch _shaheen/dynamicTransformation_. 

I also updated the ingester provider to take in the dictionary from the user of the library.

Documentation updates will follow soon.

Please take a look and let me know.

**Comment by mahmoud-syr** [comment]
Dear Shaheen,
I tried to continue implementing the report in hand, I was able finally to store data in the data warehouse with some issues. I have two suggestions in regards to the `Transformation` method:

1. Make the transformation `Func` strongly typed, there is really no need to the `object` data type as source, the data type of the source property is already known. I had to cast all of them from object to the type of the property type.
2. Add the ability to make transformation global just like services definitions because most if not all of the times I will need the same transformation rule for each data type.

All in all, I think we are on track to finally a working implementation.

**Comment by shaheensarafa** [comment]
I might look into changing NodeProperties into a generic class so that it can satisfy the typing of Transformation.

Global transformations for data types are another story, but will be looked into as well. Thank you for the feedback.

**Comment by shaheensarafa** [comment]
@mahmoud-syr Please get the latest from from `shaheen/dynamicTransformation` and let me know what you think of the new API for the HasTransformation functions.  They are documented [here](https://github.com/simplify9/FluentOlap/wiki/Transformations#variations).

You can also take a look at the unittest file if you wish, but they are present in the docs as well.

I've also added a master list for transformations, also found in the same documentation file [here](https://github.com/simplify9/FluentOlap/wiki/Transformations#transformation-master-list).

**Comment by mahmoud-syr** [comment]
@shaheensarafa I was suggesting that we use the "master list transformations" as a mapping from type (x) to type (y) and that they can be executed whenever types (x) encountered, now there is really not much of a change. The way I'm suggesting will allow my to write something like this:

`Property("LastManifest",new AnalyticalObject<ManifestDto>()).GetFromService(Configs.Services.LatestManifest, new AnalyticalObject<ManifestDto>());`

Now I'll have to do something like this instead:

```
private AnalyticalObject<ManifestDto> GenerateManifestAnalyticalObject()
{
    var manifest = new AnalyticalObject<ManifestDto>();
    manifest.Property(item => item.CreationDate).HasTransformation(dt => ((DateTime?)dt)?.ToString("yyyy-MM-dd HH:mm:ss"));
    manifest.Property(item => item.CreatedAt).HasTransformation(dt => ((DateTime)dt).ToString("yyyy-MM-dd HH:mm:ss"));
    manifest.Property(item => item.UpdatedAt).HasTransformation(dt => ((DateTime?)dt)?.ToString("yyyy-MM-dd HH:mm:ss"));
    return manifest;
}
```
And then:
`Property("LastManifest", GenerateManifestAnalyticalObject()).GetFromService(Configs.Services.LatestManifest, GenerateManifestAnalyticalObject());`

And that goes for all expandable entity that has `DateTime` properties.

The change you pushed will still require me to write almost identical code with minor changes, for example:

```
private AnalyticalObject<ManifestDto> GenerateManifestAnalyticalObject()
{
    var manifest = new AnalyticalObject<ManifestDto>();
    manifest.Property(item => item.CreationDate).HasTransformation("ToDateTransformation");
    manifest.Property(item => item.CreatedAt).HasTransformation("ToDateTransformation");
    manifest.Property(item => item.UpdatedAt).HasTransformation("ToDateTransformation");
    return manifest;
}
```
I was pointing to the fact that there are a lot of cases when you only interested about the property type, and that type should be transformed in a way that suits the DB-Engine specific type format. It's not a refactor suggestion but rather a feature, because we still need a custom transformation for other cases.

Thank you very much for the impressively fast support.

**Comment by shaheensarafa** [comment]
Ah, yes I get it. I managed keep it within the scope of the TransformationMasterList, please check out how to use it over at this [section of the docs](https://github.com/simplify9/FluentOlap/wiki/Transformations#internal-type-default-transformations). 

Let me know what you think :)

**Comment by shaheensarafa** [comment]
@mahmoud-syr any updates? :)

**Comment by mahmoud-syr** [comment]
Dear Shaheen
The current implementation worked as expected, I configured it in the following way:

```
FluentOlapConfiguration.TransformationsMasterList.AddTransformation<DateTime, string>(InternalType.DATETIME, p => ((DateTime)p).ToString("yyyy-MM-dd HH:mm:ss"));
FluentOlapConfiguration.TransformationsMasterList.AddTransformation<DateTime?, string>(InternalType.DATETIME, p => ((DateTime?)p)?.ToString("yyyy-MM-dd HH:mm:ss"));
FluentOlapConfiguration.TransformationsMasterList.AddTransformation<bool, int>(InternalType.BOOLEAN, p => ((bool)p) ? 1 : 0);
FluentOlapConfiguration.TransformationsMasterList.AddTransformation<bool?, int>(InternalType.BOOLEAN, p => (p == null ? 0 : ((bool)p) ? 1 : 0));
```

**Comment by shaheensarafa** [comment]
I'm glad this worked, but I believe that adds **2** Master Transformations, **not 4**. 

The `InternalType` is used like a key.

However, if this does satisfy the use case, please close the issue.
